jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
  
server:
  port: 8082
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/supportportal?allowPublicKeyRetrieval=true #change this to your database url
    password: "@Tn33333" #change this to your database username
    #password: root
    username: root #change this to your database password
    driver:  com.mysql.jdbc.Driver
  #profiles:
    #active: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


    